### ISSUE TITLE
Installation command line 

### ISSUE THREAD

**Issue by AEK-BKF** [bnbwebexpertise/laravel-attachments#1]
Hi,
Thanks for this good package, 
How can i install it via composer command line ?

**Comment by gabsource** [comment]
Hello,

The package is available here https://packagist.org/packages/bnbwebexpertise/laravel-attachments

`composer require bnbwebexpertise/laravel-attachments`

**Comment by AEK-BKF** [comment]
Thanks a lot for quick answer :+1:
