### ISSUE TITLE
No created directory

### ISSUE THREAD

**Issue by JakePerillano** [bnbwebexpertise/laravel-attachments#14]
Hi,
Thanks for the good package
For some reason there is no created folder when I upload images successfully, the uploaded files are saved on the attachment model but I cannot access the given filepath.

Thanks!

**Comment by gabsource** [comment]
Hi,

I see no problem using a standard L5.5 installation. Files are written in `storage/app/attachments` if no customization is applied (default storage disk / driver).

**Comment by JakePerillano** [comment]
found it. sorry about that.

Thanks!
