### ISSUE TITLE
No change filename and filepath 

### ISSUE THREAD

**Issue by anhnguyen1494** [bnbwebexpertise/laravel-attachments#15]
I want to change filepath and filename but I can not do it
Do you have a way to change it?
For example :
![image](https://user-images.githubusercontent.com/26020071/35432158-c3d2493c-02b1-11e8-94eb-802c65f847b8.png)
![image](https://user-images.githubusercontent.com/26020071/35432178-d33dd3c8-02b1-11e8-862a-5edcc81e1b7d.png)
I hope: 
![image](https://user-images.githubusercontent.com/26020071/35432000-4496a7bc-02b1-11e8-8b4f-d36096a7c2c0.png)

**Comment by gabsource** [comment]
Althought we prefer to let the system generate unique filepaths for storage we can open the `filepath` option the let the developers use it at their will.

Does the attached merge request fits your need ?

**Comment by gabsource** [comment]
```php
 $model->attach('/any/file/on/server/test.pdf', ['filepath' => 'foo/bar/demo.pdf']);
```

Will save it under `storage/foo/bar/demo.pdf`. You must provide the full filepath relative to the disk root including the filename. The configured prefix is ignored.

**Comment by anhnguyen1494** [comment]
Awesome! thank a lot
