### ISSUE TITLE
Error when to attach a file to User Model

### ISSUE THREAD

**Issue by AEK-BKF** [bnbwebexpertise/laravel-attachments#2]
Hi,

I get this error message when I tried to attach an image to a user,
Here my code :
```
$avatar = $admin->attach(public_path().'/BKF/DzErpTheme/img/default-avatar.png',[
            'disk' => 'media',
            'title' => 'avatar',
            'description' => 'default avatar',
            'key' => 'avatar'.$admin->id,
        ]);
```

and here the error :

> FatalThrowableError in Uuid.php line 66: Call to undefined function Bnb\Uuid\bcadd()

Please check it.

**Comment by gabsource** [comment]
`bcadd` is provided by `php-bcmath` extension. You can enable the extension or use a different generator via the configuration item `uuid_provider` (must be a globally available function or a static from a class in the form `Name\Space\Class@method`).

**Comment by AEK-BKF** [comment]
Where can I enable the extension ?
I'm on ubuntu 16.04 , mariadb, php 7, Laravel 5.4

**Comment by gabsource** [comment]
If not already installed you need to install the extension package. I presume something like `php7.0-bcmath`. If the extensions is installed `php7enmod bcmath` will enable it (with `sudo` if not root). 

Search for tutorials or howto, you'll easily find one for your system.

**Comment by Pes8** [comment]
Maybe the dependencies should be written in the readme ? Because I also got this error in a fresh LAMP installation (and now I've installed the extension)

**Comment by gabsource** [comment]
Thanks for reporting this. The extension dependency has been added here https://github.com/bnbwebexpertise/php-uuid/commit/bab3be737bb2867e244eceffb6aba668af51625c

Now it should throw an error when trying to install on a PHP setup without the extension.
