### ISSUE TITLE
Duplicated file on binding

### ISSUE THREAD

**Issue by Dcuevac93** [bnbwebexpertise/laravel-attachments#21]
Hi team!. I'm using **Laravel 5.4**, i installed laravel-attachments Version 0.0.16 as suggested in documentation. 

I'm storing a file usign Laravel `Storage::put()` method, then getting the url with `Storage::url(`) and then passing this path to the `$model->attach($path, $options)` method. 

Basically my problem is that once i execute `$model->attach($path, $options)`, a new file is created in the "attachments" folder. 

For this project i'm using Amazon s3 Storage and we're not about upgrading Laravel so far.

I really hope you could tell me how could i fix this or tell me what i am doing wrong.

Thanks!

**Comment by gabsource** [comment]
HI,

I don't get any file stored locally on the server when using S3 storage like this

```php
 $model->attach($someFile, [
            'disk' => 's3',
]);
```

where s3 is the name of a disk in `config/filesystems.php`:

```
       's3' => [
            'driver' => 's3',
            'key' => env('AWS_KEY'),
            'secret' => env('AWS_SECRET'),
            'region' => env('AWS_REGION'),
            'bucket' => env('AWS_BUCKET'),
        ],
```

**Comment by Dcuevac93** [comment]
Hi again! 

Excuse me, I'm not sure what kind of data do you store on `$someFile` var when you're using `s3` storage.

Thanks!

**Comment by gabsource** [comment]
The code :

```
 $model->attach($someFile, [
            'disk' => 's3',
]);
```
is used to upload a file to S3  : `$someFile` is a local path to a file or an instance of `UploadedFile`
