### ISSUE TITLE
support Carbon 2

### ISSUE THREAD

**Issue by shicosoft2011** [bnbwebexpertise/laravel-attachments#26]
- bnbwebexpertise/laravel-attachments 1.x-dev requires nesbot/carbon ~1.20 -> satisfiable by nesbot/carbon[1.20.0, 1.21.0, 1.22.0, 1.22.1, 1.23.0, 1.24.0, 1.24.1, 1.24.2, 1.25.0, 1.26.0, 1.26.1, 1.26.2, 1.26.3, 1.26.4, 1.27.0, 1.28.0, 1.29.0, 1.29.1, 1.29.2, 1.30.0, 1.31.0, 1.31.1, 1.32.0, 1.33.0, 1.34.0, 1.34.1, 1.34.2, 1.34.3, 1.34.4, 1.35.0, 1.35.1, 1.36.0, 1.36.1, 1.36.2].

**Comment by gabsource** [comment]
Dependencies updated in 1.0.12
