### ISSUE TITLE
Too many folders with dropzone.js

### ISSUE THREAD

**Issue by MWStudio4** [bnbwebexpertise/laravel-attachments#27]
Hello. Just connected lib to my project with vue-dropzone on frontend. 
I worry about too many random folders created with every uploaded file. As i read linux filesystem (ext4fs for example) become slow with too many folders (about 10000 and more). If project is quite large i think there will be even more folder amount. And i can't change this behavior (from documentation). What do you think about it? 
I found some link for ext4:
[https://ext4.wiki.kernel.org/index.php/Ext4_Howto#Sub_directory_scalability](https://ext4.wiki.kernel.org/index.php/Ext4_Howto#Sub_directory_scalability)

**Comment by gabsource** [comment]
Hi.

The default attachment model use the `getPartitionDirectory` method to build the storage path.

The default behaviour uses the first 6 chars of the uuid, splitted in two words of 3 chars, to partition the storage (2 levels of directories). The alphabet consists of 36 chars which implies a maximum number of subdirectories equal to 46656 (which is below ext4 limit).

If for any reason your use case requires another partition algorithm you can override the model class as stated at the bottom of the README and implement your own `getPartitionDirectory` method.
