### ISSUE TITLE
Not getting anything from attachments()->get()

### ISSUE THREAD

**Issue by strikermdd** [bnbwebexpertise/laravel-attachments#3]
Hi, i´m trying to generate one download button to a uploaded file. The upload its ok, i see him in the attachments table, but if i try to get all the attachments from my model, its returns nothing. 

I tried this:
$curriculo = Curriculo::find($id);      
$file = $curriculo->attachments()->get();
dd($anexos);

And it gives me a empty collection.

And yes, i can see my $id and getting my "curriculo" model fine.

Any idea how i can fix that?

**Comment by gabsource** [comment]
How do you attach the file to your model ? Are the morph columns `model_type` and `model_id` filled in the table for your attachment ?

Using `php artisan tinker` : 

```php
$user = App\User::create([
    'name' => 'name',
    'email' => 'email@foo.bar',
    'password' => 'password',
]);
$attachment = $user->attach('README.md');   // Or any other file available at project root
$user->attachments()->get();
```

Output : 

```
>>> $user->attachments()->get()
=> Illuminate\Database\Eloquent\Collection {#739
     all: [
       Bnb\Laravel\Attachments\Attachment {#718
         id: 50,
         uuid: "620q00si2t5jkpg1kyfmvnxyo",
         disk: "local",
         filepath: "attachments/620/q00/si2/620q00si2t5jkpg1kyfmvnxyo.md",
         filename: "README.md",
         filetype: "text/html",
         filesize: 2906,
         key: "58cb6c96b20bc",
         title: null,
         description: null,
         preview_url: null,
         model_id: 2,
         model_type: "App\User",
         metadata: null,
         created_at: "2017-03-17 04:56:54",
         updated_at: "2017-03-17 04:56:54",
       },
     ],
   }
```

**Comment by gabsource** [comment]
By the way, in your message you `dd($anexos)` but the collection is in the `$file`. Maybe it's just a typo from copy-paste.

**Comment by strikermdd** [comment]
yes, was a typo, i´m trying to get the collection from $file, and the colums model_type and model_id, its filled ok in the database. But returns null if i try to get by the key, and a empty collection if i try to find by attachments()->get();

**Comment by gabsource** [comment]
If your model uses the `HasAttachment` trait the collection should not be empty. 

I can't reproduce your problem. Added the trait to the stock `User` model, tested with tinker as above, the collection is not empty.

**Comment by strikermdd** [comment]
My Model: 
<?php
namespace App\Models\Extras;

use Bnb\Laravel\Attachments\HasAttachment;
use Illuminate\Database\Eloquent\Model;

class Curriculo extends Model {
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'curriculos';
    
    use HasAttachment;

}

**Comment by strikermdd** [comment]
And my return to this code :
`public function getCurriculo($id) {
        
        $curriculo = Curriculo::find($id);
        
        $anexos = $curriculo->attachments()->get();

        dd($anexos);
        
    }`

Is:

`Collection {#555 ▼
  #items: []
}`

**Comment by gabsource** [comment]
if the `$id` you use matches a `model_id` with a `model_type` that correspond to the full namespace name of your `Curriculo` class the collection shouldn't be empty.


Here is my test code that works as expected (files added to the lis) :

The stock User class where I added the `HasAttachment` trait  :
 
The model:
```php
class User extends Authenticatable
{
    use Notifiable, HasAttachment;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}
```

The routes:
```php
Route::get('/single', function () {
    return view('single')->with('files', App\User::first()->attachments()->get());
});

Route::post('/single', function () {
    App\User::first()->attach(Request::file('file'), [
        'title' => Request::input('title'),
        'disk' => 'local',
    ]);

    return redirect('/single');
});
```

The view:
```html
        <form action="/single" method="post" enctype="multipart/form-data">
            {{ csrf_field() }}
            <input type="text" name="title" placeholder="title">
            <br>
            <input type="file" name="file">
            <button type="submit">Save</button>
        </form>

        <ul>
            @foreach($files as $file)
                <li>
                    <a href="{{ $file->url }}">{{ $file->title ?: $file->filename }}</a>
                </li>
            @endforeach
        </ul>
```

**Comment by strikermdd** [comment]
Well i don´t know anymore, i´m making anything like you said, and it gives me a empty collection.

I´m using for example : http://mydomain.com/site/extras/curriculos/download/3 (were 3 its the id of one of my "curriculos"). I access that "curriculo" with dd($curriculo) just fine. Only the attachments don´t work.

Try to create another model, in another directory (for example: app/models/example/Example.php) and test please. (maybe some problem with custom directory for models ...)
