### ISSUE TITLE
Deleted attachments not deleting from s3 when filesystems.default = local

### ISSUE THREAD

**Issue by jschlies** [bnbwebexpertise/laravel-attachments#6]
See attached unit test and conf file.
1. Set filesystems.default = local
1. Set 'attachments.behavior.cascade_delete = true
1. Create an object
1. Add attachments as in attached unit test
1. Confirm records exist DATABASE.attachments (see attached)
![attachment_table](https://cloud.githubusercontent.com/assets/2206903/26065836/e84bf75e-3949-11e7-8cfb-885e0af527a1.png)

1. Confirm they are saved to AWS s3
1. Delete attachments
1. Delete object
1. Confirm records are deleted from DATABASE.attachments
1. Confirm they are STILL saved to AWS s3

If I repeat the steps above but change  filesystems.default = s3, files are deleted in BOTH DATABASE.attachments and aws.s3 (expected behavior)

[OpportunityRepositoryTest.php.txt](https://github.com/bnbwebexpertise/laravel-attachments/files/1001540/OpportunityRepositoryTest.php.txt)
[attachments.php.txt](https://github.com/bnbwebexpertise/laravel-attachments/files/1001541/attachments.php.txt)
[filesystems.php.txt](https://github.com/bnbwebexpertise/laravel-attachments/files/1001542/filesystems.php.txt)

**Comment by jschlies** [comment]
Also I would expect that the file on s3 would be explicitly then file with same key is uploaded if only to see that the related events fire as expected though I also this this a separate issue.

**Comment by gabsource** [comment]
Hi,

Thanks for reporting this. The disk used was not read from the record data.

Concerning your second comment, open a separate issue for it if necessary. I think you want a "delete + store " instead of a simple "store" that erase the file on the storage.

**Comment by jschlies** [comment]
Thanks for the prompt response. BTW, are you accepting pull reqs?

**Comment by gabsource** [comment]
Sure, for bugfixes and general purpose features.
