### ISSUE TITLE
Best way to handle multiple file uploads? 

### ISSUE THREAD

**Issue by devingray** [bnbwebexpertise/laravel-attachments#7]
I see there is a hidden field that we can update and attach the file in the controller on save, which is beautiful logic. just want to find out what the best approach for multiple uploads with dropzone would be

**Comment by gabsource** [comment]
Hi,

How you handle this is up to you and what fits best for your project. The simplest approach to me would be the following.

You can add to your form a new `<input type="hidden" name="attachements[]" value="[your_uploaded_file_id]">` for each successfully uploaded file (in the dropzone callback).

You get all the IDs on server side as a table `$request->input('attachements')` and you can attach all of them to your model (after it is saved).

**Comment by devingray** [comment]
Perfect, yeah I had done something similar, initially I cached them and tried to get them from there but appending them to an array is much better. Thanks
